Repository swing-park/issue-tracker, pull requests merged in 2021-06, with the labels that each got.

#12 feat: :sparkles: Header 뷰 완성 #5
  FE/issue-tracker/package.json
  FE/issue-tracker/src/App.tsx
  FE/issue-tracker/src/Components/Header/Header.tsx
  FE/issue-tracker/src/Components/Header/HeaderStyles.tsx
  FE/issue-tracker/src/Styles/GlobalStyles.tsx
  FE/issue-tracker/yarn.lock
Labels: FE, feature

#13 [iOS] change build target
  iOS/issue-tracker/Podfile.lock
  iOS/issue-tracker/issue-tracker.xcodeproj/project.pbxproj
  iOS/issue-tracker/issue-tracker/AppDelegate.swift
  iOS/issue-tracker/issue-tracker/Model/Endpoint.swift
  iOS/issue-tracker/issue-tracker/Model/NetworkManager.swift
  iOS/issue-tracker/issue-tracker/SceneDelegate.swift
  iOS/issue-tracker/issue-tracker/Supporting Files/AppDelegate.swift
  iOS/issue-tracker/issue-tracker/Supporting Files/Assets.xcassets/AccentColor.colorset/Contents.json
  iOS/issue-tracker/issue-tracker/Supporting Files/Assets.xcassets/AppIcon.appiconset/Contents.json
  iOS/issue-tracker/issue-tracker/Supporting Files/Assets.xcassets/Contents.json
  iOS/issue-tracker/issue-tracker/Supporting Files/Base.lproj/LaunchScreen.storyboard
  iOS/issue-tracker/issue-tracker/Supporting Files/SceneDelegate.swift
Labels: iOS

#16 [iOS] LoginView
  iOS/issue-tracker/Podfile.lock
  iOS/issue-tracker/issue-tracker.xcodeproj/project.pbxproj
  iOS/issue-tracker/issue-tracker/Base.lproj/Main.storyboard
  iOS/issue-tracker/issue-tracker/LoginViewController.swift
  iOS/issue-tracker/issue-tracker/Supporting Files/AppDelegate.swift
  iOS/issue-tracker/issue-tracker/Supporting Files/Assets.xcassets/apple.imageset/Contents.json
  iOS/issue-tracker/issue-tracker/Supporting Files/Assets.xcassets/apple.imageset/unnamed.jpg
  iOS/issue-tracker/issue-tracker/Supporting Files/Assets.xcassets/github.imageset/9919.png
  iOS/issue-tracker/issue-tracker/Supporting Files/Assets.xcassets/github.imageset/Contents.json
  iOS/issue-tracker/issue-tracker/View/AppleLoginButton.swift
  iOS/issue-tracker/issue-tracker/View/GitHubLoginButton.swift
  iOS/issue-tracker/issue-tracker/View/IDPasswordTextField.swift
  iOS/issue-tracker/issue-tracker/View/LoginView.swift
Labels: iOS

#19 [iOS] Tab Bar Controller
  iOS/issue-tracker/issue-tracker/Base.lproj/Main.storyboard
  iOS/issue-tracker/issue-tracker/Supporting Files/Assets.xcassets/Vector.imageset/Contents.json
  iOS/issue-tracker/issue-tracker/Supporting Files/Assets.xcassets/Vector.imageset/Vector.png
Labels: feature, iOS

#22 Fe/feature/#6/home view
  FE/issue-tracker/src/Components/AtomicComponents/Label.tsx
  FE/issue-tracker/src/Components/AtomicComponents/UserProfile.tsx
  FE/issue-tracker/src/Components/Header/Header.tsx
  FE/issue-tracker/src/Components/Home/HomeContents/CreateIssueButton.tsx
  FE/issue-tracker/src/Components/Home/HomeContents/Filter/Filter.tsx
  FE/issue-tracker/src/Components/Home/HomeContents/IssueSearchBar.tsx
  FE/issue-tracker/src/Components/Home/HomeContents/IssueTable/IssueTableBody/IssueTableBody.tsx
  FE/issue-tracker/src/Components/Home/HomeContents/IssueTable/IssueTableBody/IssueTableRow/CheckButton.tsx
  FE/issue-tracker/src/Components/Home/HomeContents/IssueTable/IssueTableBody/IssueTableRow/IssueDescription.tsx
  FE/issue-tracker/src/Components/Home/HomeContents/IssueTable/IssueTableBody/IssueTableRow/IssueDropDownSymbol.tsx
  FE/issue-tracker/src/Components/Home/HomeContents/IssueTable/IssueTableBody/IssueTableRow/IssueLabel.tsx
  FE/issue-tracker/src/Components/Home/HomeContents/IssueTable/IssueTableBody/IssueTableRow/IssueTableRow.tsx
  FE/issue-tracker/src/Components/Home/HomeContents/IssueTable/IssueTableBody/IssueTableRow/IssueTitle.tsx
  FE/issue-tracker/src/Components/Home/HomeContents/IssueTable/IssueTableHeader/IssueDropDownCategory.tsx
  FE/issue-tracker/src/Components/Home/HomeContents/IssueTable/IssueTableHeader/IssueToggleCategory.tsx
  FE/issue-tracker/src/Components/Home/HomeContents/LabelButton.tsx
  FE/issue-tracker/src/Components/Home/HomeContents/MileStoneButton.tsx
  FE/issue-tracker/src/Components/Home/HomeStyles.tsx
  FE/issue-tracker/src/Routes/MainPage.tsx
  FE/issue-tracker/src/Routes/Router.tsx
  FE/issue-tracker/src/Styles/GlobalStyles.tsx
  FE/issue-tracker/src/assets/svg/Down.svg
  FE/issue-tracker/src/assets/svg/IssueMark.svg
  FE/issue-tracker/src/assets/svg/Search.svg
  FE/issue-tracker/src/assets/svg/closeIssueMark.svg
  FE/issue-tracker/src/assets/svg/labelTag.svg
  FE/issue-tracker/src/assets/svg/milestoneTag.svg
Labels: FE

#26 [iOS] LabelTabView
  iOS/issue-tracker/issue-tracker.xcodeproj/project.pbxproj
  iOS/issue-tracker/issue-tracker/Base.lproj/Main.storyboard
  iOS/issue-tracker/issue-tracker/Extension/UIColor+HexInit.swift
  iOS/issue-tracker/issue-tracker/LabelTableViewCell.swift
  iOS/issue-tracker/issue-tracker/View/AddButton.swift
  iOS/issue-tracker/issue-tracker/View/LabelTabelHeaderView.swift
  iOS/issue-tracker/issue-tracker/View/LabelViewController.swift
  iOS/issue-tracker/issue-tracker/View/Login/AppleLoginButton.swift
  iOS/issue-tracker/issue-tracker/View/Login/GitHubLoginButton.swift
  iOS/issue-tracker/issue-tracker/View/Login/IDPasswordTextField.swift
  iOS/issue-tracker/issue-tracker/View/Login/LoginView.swift
  iOS/issue-tracker/issue-tracker/View/PaddingLabel.swift
Labels: feature, iOS

#25 Fe/feature/23/drop down menu
  FE/issue-tracker/package-lock.json
  FE/issue-tracker/src/Components/AtomicComponents/AtomicComponentsStyles.tsx
  FE/issue-tracker/src/Components/AtomicComponents/Label.tsx
  FE/issue-tracker/src/Components/AtomicComponents/Modal/Modal.tsx
  FE/issue-tracker/src/Components/AtomicComponents/Modal/ModalCheckButton.tsx
  FE/issue-tracker/src/Components/AtomicComponents/Modal/ModalItem.tsx
  FE/issue-tracker/src/Components/AtomicComponents/UserProfile.tsx
  FE/issue-tracker/src/Components/Header/Header.tsx
  FE/issue-tracker/src/Components/Home/HomeContents/Filter/Filter.tsx
  FE/issue-tracker/src/Components/Home/HomeContents/Filter/FilterModal.tsx
  FE/issue-tracker/src/Components/Home/HomeContents/IssueTable/IssueTableBody/IssueTableBody.tsx
  FE/issue-tracker/src/Components/Home/HomeContents/IssueTable/IssueTableBody/IssueTableRow/CheckButton.tsx
  FE/issue-tracker/src/Components/Home/HomeContents/IssueTable/IssueTableBody/IssueTableRow/IssueTableRow.tsx
  FE/issue-tracker/src/Components/Home/HomeStore.tsx
Labels: FE, feature

#29 [iOS] Issue Filter View
  iOS/issue-tracker/issue-tracker/Controller/AddViewController.swift
  iOS/issue-tracker/issue-tracker/Controller/IssueFilterViewController.swift
  iOS/issue-tracker/issue-tracker/Controller/MilestoneViewController.swift
  iOS/issue-tracker/issue-tracker/View/Milestone/MilestoneTableViewCell.swift
Labels: feature, iOS

#31 Fe/feature/7/milestone view
  FE/issue-tracker/src/App.tsx
  FE/issue-tracker/src/Components/AtomicComponents/AtomicComponentsStyles.tsx
  FE/issue-tracker/src/Components/Header/Header.tsx
  FE/issue-tracker/src/Components/Home/HomeContents/HomeContents.tsx
  FE/issue-tracker/src/Components/Home/HomeContents/IssueTable/IssueTableBody/IssueTableRow/CheckButton.tsx
  FE/issue-tracker/src/Components/Login/LoginForm/Input.tsx
  FE/issue-tracker/src/Components/Login/LoginForm/LoginButton.tsx
  FE/issue-tracker/src/Components/Login/LoginForm/SignUpButton.tsx
  FE/issue-tracker/src/Components/Login/SocialLoginButton.tsx
  FE/issue-tracker/src/Components/NewIssue/NewIssue.tsx
  FE/issue-tracker/src/Components/Tab/Tab.tsx
  FE/issue-tracker/src/Components/Tab/TabContents/TabContentRow/ContentDescription.tsx
  FE/issue-tracker/src/Components/Tab/TabContents/TabContentRow/ContentTitle.tsx
  FE/issue-tracker/src/Components/Tab/TabContents/TabContentRow/DeleteButton.tsx
  FE/issue-tracker/src/Components/Tab/TabContents/TabContentRow/EditButton.tsx
  FE/issue-tracker/src/Components/Tab/TabContents/TabContentRow/EditInput.tsx
  FE/issue-tracker/src/Components/Tab/TabContents/TabContentRow/RangeBar.tsx
  FE/issue-tracker/src/Components/Tab/TabContents/TabContentRow/RangeDescription.tsx
  FE/issue-tracker/src/Components/Tab/TabContents/TabContentRow/TabContentRow.tsx
  FE/issue-tracker/src/Components/Tab/TabContents/TabContents.tsx
  FE/issue-tracker/src/Components/Tab/TabContents/TabContentsHeader.tsx
  FE/issue-tracker/src/Components/Tab/TabContents/TabContentsTitle.tsx
  FE/issue-tracker/src/Components/Tab/TabHeader/AddTabButton.tsx
  FE/issue-tracker/src/Components/Tab/TabHeader/TabContents/TabContent/EditButton.tsx
  FE/issue-tracker/src/Components/Tab/TabHeader/TabContents/TabContent/EditInput.tsx
  FE/issue-tracker/src/Components/Tab/TabHeader/TabContents/TabContent/RangeBar.tsx
  FE/issue-tracker/src/Components/Tab/TabHeader/TabContents/TabContent/RangeDescription.tsx
  FE/issue-tracker/src/Components/Tab/TabHeader/TabContents/TabContent/TabContent.tsx
  FE/issue-tracker/src/Components/Tab/TabHeader/TabHeader.tsx
  FE/issue-tracker/src/Components/Tab/TabModal/LabelAddModal.tsx
  FE/issue-tracker/src/Components/Tab/TabModal/LabelEditModal.tsx
  FE/issue-tracker/src/Components/Tab/TabStore.tsx
  FE/issue-tracker/src/Components/Tab/TabStyles.tsx
  FE/issue-tracker/src/Routes/Router.tsx
  FE/issue-tracker/src/Routes/TabPage.tsx
  FE/issue-tracker/src/assets/svg/Edit.svg
  FE/issue-tracker/src/assets/svg/Refresh.svg
  FE/issue-tracker/src/assets/svg/Trash.svg
Labels: FE, feature

#32 [iOS] New Issue 추가 화면 구현
  iOS/issue-tracker/issue-tracker.xcodeproj/project.pbxproj
  iOS/issue-tracker/issue-tracker.xcworkspace/xcshareddata/swiftpm/Package.resolved
  iOS/issue-tracker/issue-tracker/Controller/IssueDetailViewController.swift
  iOS/issue-tracker/issue-tracker/Controller/MilestoneViewController.swift
  iOS/issue-tracker/issue-tracker/Controller/NewIssueViewController.swift
Labels: feature, iOS

#33 Fe/feature/7/milestone view
  FE/issue-tracker/src/Components/AtomicComponents/AtomicComponentsStyles.tsx
  FE/issue-tracker/src/Components/AtomicComponents/Label.tsx
  FE/issue-tracker/src/Components/AtomicComponents/Modal/ModalCheckButton.tsx
  FE/issue-tracker/src/Components/Home/HomeContents/Filter/Filter.tsx
  FE/issue-tracker/src/Components/Home/HomeContents/Filter/FilterModal.tsx
  FE/issue-tracker/src/Components/Home/HomeContents/IssueTable/IssueTableBody/IssueTableBody.tsx
  FE/issue-tracker/src/Components/Home/HomeContents/IssueTable/IssueTableBody/IssueTableRow/CheckButton.tsx
  FE/issue-tracker/src/Components/Home/HomeContents/IssueTable/IssueTableBody/IssueTableRow/IssueLabel.tsx
  FE/issue-tracker/src/Components/Home/HomeContents/IssueTable/IssueTableBody/IssueTableRow/IssueTitle.tsx
  FE/issue-tracker/src/Components/Home/HomeStyles.tsx
  FE/issue-tracker/src/Components/NewIssue/NewIssue.tsx
  FE/issue-tracker/src/Components/SettingSideBar/SettingDropDown/ItemCheckBox.tsx
  FE/issue-tracker/src/Components/Tab/Tab.tsx
  FE/issue-tracker/src/Components/Tab/TabContents/TabContentRow/EditButton.tsx
  FE/issue-tracker/src/Components/Tab/TabContents/TabContentRow/TabContentRow.tsx
  FE/issue-tracker/src/Components/Tab/TabContents/TabContents.tsx
  FE/issue-tracker/src/Components/Tab/TabModal/Label/LabelAddModal.tsx
  FE/issue-tracker/src/Components/Tab/TabModal/Label/LabelEditModal.tsx
  FE/issue-tracker/src/Components/Tab/TabStore.tsx
Labels: FE, fix

#35 [iOS] Issue Detail 화면
  iOS/issue-tracker/issue-tracker.xcodeproj/project.pbxproj
  iOS/issue-tracker/issue-tracker/Controller/IssueDetailViewController.swift
  iOS/issue-tracker/issue-tracker/View/IssueDetailTableViewCell.swift
Labels: feature, iOS

#37 [iOS] complement issue view
  iOS/issue-tracker/issue-tracker.xcodeproj/project.pbxproj
  iOS/issue-tracker/issue-tracker/Controller/IssueFilterViewController.swift
  iOS/issue-tracker/issue-tracker/Controller/NewIssueViewController.swift
  iOS/issue-tracker/issue-tracker/View/IssueListViewController.swift
Labels: feature, iOS

#39 Fe/feature/36/home modal
  FE/issue-tracker/src/Components/Home/HomeContents/Filter/Filter.tsx
  FE/issue-tracker/src/Components/Home/HomeContents/Filter/FilterModal.tsx
  FE/issue-tracker/src/Components/Home/HomeContents/IssueTable/IssueTableHeader/DropDown/DropDown.tsx
  FE/issue-tracker/src/Components/Home/HomeContents/IssueTable/IssueTableHeader/IssueDropDownCategory.tsx
  FE/issue-tracker/src/Components/Home/HomeStore.tsx
  FE/issue-tracker/src/Components/Home/HomeStyles.tsx
Labels: FE

#41 [iOS] DTO 모델 구현
  iOS/issue-tracker/issue-tracker.xcodeproj/project.pbxproj
  iOS/issue-tracker/issue-tracker/Model/UserDTO/Comment.swift
  iOS/issue-tracker/issue-tracker/Model/UserDTO/IssueList.swift
  iOS/issue-tracker/issue-tracker/Model/UserDTO/MilestoneList.swift
  iOS/issue-tracker/issue-tracker/Model/UserDTO/NewIssue.swift
  iOS/issue-tracker/issue-tracker/Model/UserDTO/UserList.swift
  iOS/issue-tracker/issue-tracker/Supporting Files/Assets.xcassets/Vector.imageset/Contents.json
  iOS/issue-tracker/issue-tracker/Supporting Files/Assets.xcassets/Vector.imageset/Vector.png
  iOS/issue-tracker/issue-tracker/View/IssueList/IssueTableViewCell.swift
Labels: feature, iOS

#57 Fe/feature/56/label mile
  FE/issue-tracker/src/Components/Home/HomeContents/MileStoneButton.tsx
  FE/issue-tracker/src/Components/Tab/TabHeader/AddTabButton.tsx
  FE/issue-tracker/src/Components/Tab/TabModal/Label/EditLabelView.tsx
  FE/issue-tracker/src/Components/Tab/TabModal/Label/LabelAddModal.tsx
  FE/issue-tracker/src/Components/Tab/TabModal/Label/LabelEditModal.tsx
  FE/issue-tracker/src/Components/Tab/TabModal/Label/NewLabelView.tsx
  FE/issue-tracker/src/Components/Tab/TabStore.tsx
  FE/issue-tracker/src/Components/Tab/TabStyles.tsx
Labels: FE, enhancement, feature

#66 [BE] milestone
  BE/issuetracker/src/main/java/com/codesquad/issuetracker/controller/MilestoneController.java
  BE/issuetracker/src/main/java/com/codesquad/issuetracker/domain/Milestone.java
  BE/issuetracker/src/main/java/com/codesquad/issuetracker/dto/milestone/MilestoneDTO.java
  BE/issuetracker/src/main/java/com/codesquad/issuetracker/dto/milestone/MilestoneRequest.java
  BE/issuetracker/src/main/java/com/codesquad/issuetracker/repository/MilestoneRepository.java
  BE/issuetracker/src/main/java/com/codesquad/issuetracker/service/MilestoneService.java
Labels: BE

#67 [BE] Label
  BE/issuetracker/src/main/java/com/codesquad/issuetracker/controller/LabelController.java
  BE/issuetracker/src/main/java/com/codesquad/issuetracker/domain/Label.java
  BE/issuetracker/src/main/java/com/codesquad/issuetracker/dto/label/LabelDTO.java
  BE/issuetracker/src/main/java/com/codesquad/issuetracker/dto/label/LabelRequest.java
  BE/issuetracker/src/main/java/com/codesquad/issuetracker/repository/LabelRepository.java
  BE/issuetracker/src/main/java/com/codesquad/issuetracker/service/LabelService.java
Labels: BE

#75 [iOS] Modify AccessControl
  iOS/issue-tracker/LabelsCollectionViewCell.swift
  iOS/issue-tracker/issue-tracker/Controller/AddLabelViewController.swift
  iOS/issue-tracker/issue-tracker/Controller/IssueTableFooterView.swift
  iOS/issue-tracker/issue-tracker/Controller/IssueToolbar.swift
  iOS/issue-tracker/issue-tracker/Controller/LabelViewController.swift
  iOS/issue-tracker/issue-tracker/Controller/NewIssueViewController.swift
  iOS/issue-tracker/issue-tracker/View/IssueList/AddIssueButton.swift
  iOS/issue-tracker/issue-tracker/View/IssueList/CancelButton.swift
  iOS/issue-tracker/issue-tracker/View/IssueList/FilterBarButton.swift
  iOS/issue-tracker/issue-tracker/View/IssueList/IssueTableViewCell.swift
  iOS/issue-tracker/issue-tracker/View/IssueList/LabelsCollectionView.swift
  iOS/issue-tracker/issue-tracker/View/IssueList/MilestoneView.swift
  iOS/issue-tracker/issue-tracker/View/IssueList/SelectBarButton.swift
  iOS/issue-tracker/issue-tracker/View/IssueList/ToolBarTextField.swift
  iOS/issue-tracker/issue-tracker/View/IssueListViewController.swift
  iOS/issue-tracker/issue-tracker/View/Label/AddLabelButton.swift
  iOS/issue-tracker/issue-tracker/View/Label/AddTableViewCell.swift
  iOS/issue-tracker/issue-tracker/View/Label/EstimatedLabelView.swift
  iOS/issue-tracker/issue-tracker/View/Label/LabelTableViewCell.swift
  iOS/issue-tracker/issue-tracker/View/Label/PaddingLabel.swift
Labels: iOS

#76 Fe/feature/jen p ract2
  FE/issue-tracker/package.json
  FE/issue-tracker/src/App.tsx
  FE/issue-tracker/src/Components/AtomicComponents/AtomicComponentsStyles.tsx
  FE/issue-tracker/src/Components/Home/HomeContents/IssueTable/IssueTableBody/IssueTableBody.tsx
  FE/issue-tracker/src/Components/Home/HomeContents/IssueTable/IssueTableBody/IssueTableRow/IssueDescription.tsx
  FE/issue-tracker/src/Components/Home/HomeContents/IssueTable/IssueTableBody/IssueTableRow/IssueTableRow.tsx
  FE/issue-tracker/src/Components/Home/HomeContents/IssueTable/IssueTableHeader/TotalIssueCheckButton.tsx
  FE/issue-tracker/src/Routes/Callback.tsx
  FE/issue-tracker/src/Routes/MyRecoilTest.tsx
  FE/issue-tracker/src/Routes/Router.tsx
  FE/issue-tracker/src/Utils/MyRecoil/RecoilRoot.tsx
  FE/issue-tracker/src/Utils/MyRecoil/myRecoil.ts
  FE/issue-tracker/src/Utils/MyRecoil/useMycoilState.tsx
  FE/issue-tracker/src/Utils/MyRecoil/useMycoilValue.tsx
  FE/issue-tracker/src/stores/HomeAtoms.tsx
Labels: FE, enhancement

#81 이슈 관련 API
  BE/issuetracker/src/main/java/com/codesquad/issuetracker/controller/IssueController.java
  BE/issuetracker/src/main/java/com/codesquad/issuetracker/controller/LabelController.java
  BE/issuetracker/src/main/java/com/codesquad/issuetracker/controller/MilestoneController.java
  BE/issuetracker/src/main/java/com/codesquad/issuetracker/domain/Comment.java
  BE/issuetracker/src/main/java/com/codesquad/issuetracker/domain/Issue.java
  BE/issuetracker/src/main/java/com/codesquad/issuetracker/domain/Label.java
  BE/issuetracker/src/main/java/com/codesquad/issuetracker/domain/Milestone.java
  BE/issuetracker/src/main/java/com/codesquad/issuetracker/dto/CommentDTO.java
  BE/issuetracker/src/main/java/com/codesquad/issuetracker/dto/CommentRequest.java
  BE/issuetracker/src/main/java/com/codesquad/issuetracker/dto/UserDTO.java
  BE/issuetracker/src/main/java/com/codesquad/issuetracker/dto/issue/DetailedIssue.java
  BE/issuetracker/src/main/java/com/codesquad/issuetracker/dto/issue/IssueResponse.java
  BE/issuetracker/src/main/java/com/codesquad/issuetracker/dto/issue/request/IssueRequest.java
  BE/issuetracker/src/main/java/com/codesquad/issuetracker/dto/issue/request/IssueStatusRequest.java
  BE/issuetracker/src/main/java/com/codesquad/issuetracker/dto/label/LabelDTO.java
  BE/issuetracker/src/main/java/com/codesquad/issuetracker/dto/label/LabelRequest.java
  BE/issuetracker/src/main/java/com/codesquad/issuetracker/dto/milestone/MilestoneDTO.java
  BE/issuetracker/src/main/java/com/codesquad/issuetracker/dto/milestone/MilestoneRequest.java
  BE/issuetracker/src/main/java/com/codesquad/issuetracker/exception/NotFoundException.java
  BE/issuetracker/src/main/java/com/codesquad/issuetracker/repository/IssueRepository.java
  BE/issuetracker/src/main/java/com/codesquad/issuetracker/repository/LabelRepository.java
  BE/issuetracker/src/main/java/com/codesquad/issuetracker/repository/MilestoneRepository.java
  BE/issuetracker/src/main/java/com/codesquad/issuetracker/repository/UserRepository.java
  BE/issuetracker/src/main/java/com/codesquad/issuetracker/service/IssueService.java
  BE/issuetracker/src/main/java/com/codesquad/issuetracker/service/LabelService.java
  BE/issuetracker/src/main/java/com/codesquad/issuetracker/service/MilestoneService.java
  BE/issuetracker/src/main/java/com/codesquad/issuetracker/service/UserService.java
Labels: BE, enhancement

#82 Refactor on issue api and etc
  BE/issuetracker/src/main/java/com/codesquad/issuetracker/config/WebMvcConfig.java
  BE/issuetracker/src/main/java/com/codesquad/issuetracker/controller/LabelController.java
  BE/issuetracker/src/main/java/com/codesquad/issuetracker/controller/MilestoneController.java
  BE/issuetracker/src/main/java/com/codesquad/issuetracker/controller/UserController.java
  BE/issuetracker/src/main/java/com/codesquad/issuetracker/domain/Comment.java
  BE/issuetracker/src/main/java/com/codesquad/issuetracker/domain/Milestone.java
  BE/issuetracker/src/main/java/com/codesquad/issuetracker/domain/User.java
  BE/issuetracker/src/main/java/com/codesquad/issuetracker/service/oauthService/GithubOauthService.java
  BE/issuetracker/src/main/java/com/codesquad/issuetracker/service/oauthService/GoogleOauthService.java
  BE/issuetracker/src/main/java/com/codesquad/issuetracker/service/oauthService/OauthService.java
  BE/issuetracker/src/test/java/com/codesquad/issuetracker/service/IssueServiceTest.java
Labels: BE, enhancement

#90 Fe/feature/78/label mile data
  FE/issue-tracker/src/Components/AtomicComponents/Label.tsx
  FE/issue-tracker/src/Components/AtomicComponents/Modal/ModalCheckButton.tsx
  FE/issue-tracker/src/Components/Home/HomeContents/Filter/Filter.tsx
  FE/issue-tracker/src/Components/Home/HomeContents/Filter/FilterModal.tsx
  FE/issue-tracker/src/Components/Home/HomeContents/IssueSearchBar.tsx
  FE/issue-tracker/src/Components/Home/HomeContents/IssueTable/IssueTableBody/IssueTableBody.tsx
  FE/issue-tracker/src/Components/Home/HomeContents/IssueTable/IssueTableBody/IssueTableRow/CheckButton.tsx
  FE/issue-tracker/src/Components/Home/HomeContents/IssueTable/IssueTableHeader/DropDown/DropDown.tsx
  FE/issue-tracker/src/Components/Home/HomeContents/IssueTable/IssueTableHeader/DropDown/StateDropDown.tsx
  FE/issue-tracker/src/Components/Home/HomeContents/IssueTable/IssueTableHeader/IssueDropDownCategory.tsx
  FE/issue-tracker/src/Components/Home/HomeContents/IssueTable/IssueTableHeader/IssueTableHeader.tsx
  FE/issue-tracker/src/Components/Home/HomeContents/IssueTable/IssueTableHeader/TotalIssueCheckButton.tsx
  FE/issue-tracker/src/Components/Tab/Tab.tsx
  FE/issue-tracker/src/Components/Tab/TabContents/TabContentRow/ContentDescription.tsx
  FE/issue-tracker/src/Components/Tab/TabContents/TabContentRow/ContentTitle.tsx
  FE/issue-tracker/src/Components/Tab/TabContents/TabContentRow/EditButton.tsx
  FE/issue-tracker/src/Components/Tab/TabContents/TabContentRow/RangeDescription.tsx
  FE/issue-tracker/src/Components/Tab/TabContents/TabContentRow/TabContentRow.tsx
  FE/issue-tracker/src/Components/Tab/TabContents/TabContents.tsx
  FE/issue-tracker/src/Components/Tab/TabContents/TabContentsHeader.tsx
  FE/issue-tracker/src/Components/Tab/TabHeader/AddTabButton.tsx
  FE/issue-tracker/src/Components/Tab/TabHeader/TabHeader.tsx
  FE/issue-tracker/src/Components/Tab/TabModal/Label/EditLabelView.tsx
  FE/issue-tracker/src/Components/Tab/TabModal/Label/LabelAddModal.tsx
  FE/issue-tracker/src/Components/Tab/TabModal/Label/LabelEditModal.tsx
  FE/issue-tracker/src/Components/Tab/TabModal/Label/NewLabelView.tsx
  FE/issue-tracker/src/Components/Tab/TabModal/Milestone/MilestoneAddModal.tsx
  FE/issue-tracker/src/Components/Tab/TabModal/Milestone/MilestoneEditModal.tsx
  FE/issue-tracker/src/Components/Tab/TabTypes.ts
  FE/issue-tracker/src/Utils/MyRecoil/useMycoilState.tsx
  FE/issue-tracker/src/Utils/api.ts
  FE/issue-tracker/src/Utils/useFetch.ts
  FE/issue-tracker/src/stores/TabAtoms.tsx
Labels: FE, enhancement

#95 Fe/feature/77/filter issue
  FE/issue-tracker/src/Components/AtomicComponents/Modal/Modal.tsx
  FE/issue-tracker/src/Components/AtomicComponents/Modal/ModalCheckButton.tsx
  FE/issue-tracker/src/Components/AtomicComponents/Modal/ModalItem.tsx
  FE/issue-tracker/src/Components/Home/HomeContents/IssueSearchBar.tsx
  FE/issue-tracker/src/Components/Home/HomeContents/IssueTable/IssueTableBody/IssueTableBody.tsx
  FE/issue-tracker/src/Components/Home/HomeContents/IssueTable/IssueTableBody/IssueTableRow/IssueDescription.tsx
  FE/issue-tracker/src/Components/Home/HomeContents/IssueTable/IssueTableBody/IssueTableRow/IssueDropDownSymbol.tsx
  FE/issue-tracker/src/Components/Home/HomeContents/IssueTable/IssueTableBody/IssueTableRow/IssueLabel.tsx
  FE/issue-tracker/src/Components/Home/HomeContents/IssueTable/IssueTableBody/IssueTableRow/IssueTableRow.tsx
  FE/issue-tracker/src/Components/Home/HomeContents/IssueTable/IssueTableHeader/DropDown/DropDown.tsx
  FE/issue-tracker/src/Components/Home/HomeContents/IssueTable/IssueTableHeader/IssueDropDownCategory.tsx
  FE/issue-tracker/src/Components/Home/HomeContents/IssueTable/IssueTableHeader/TotalIssueCheckButton.tsx
  FE/issue-tracker/src/Components/Home/homeTypes.ts
  FE/issue-tracker/src/Components/Tab/TabContents/TabContentRow/EditButton.tsx
  FE/issue-tracker/src/Components/Tab/TabContents/TabContents.tsx
  FE/issue-tracker/src/Components/Tab/TabContents/TabContentsHeader.tsx
  FE/issue-tracker/src/Components/Tab/TabHeader/TabHeader.tsx
  FE/issue-tracker/src/Components/Tab/TabModal/Milestone/MilestoneAddModal.tsx
  FE/issue-tracker/src/Components/Tab/TabModal/Milestone/MilestoneEditModal.tsx
  FE/issue-tracker/src/Utils/filterData.ts
  FE/issue-tracker/src/Utils/useFetch.ts
  FE/issue-tracker/src/stores/homeAtoms.tsx
  FE/issue-tracker/src/stores/tabAtoms.tsx
Labels: FE, feature

#96 Fe/feature/94/label mile delete
  FE/issue-tracker/src/Components/Tab/Tab.tsx
  FE/issue-tracker/src/Components/Tab/TabContents/TabContentRow/DeleteButton.tsx
  FE/issue-tracker/src/Components/Tab/TabContents/TabContentRow/TabContentRow.tsx
  FE/issue-tracker/src/Components/Tab/TabContents/TabContents.tsx
  FE/issue-tracker/src/Utils/api.ts
Labels: FE, feature

#97 [iOS] Complement UI
  iOS/issue-tracker/issue-tracker.xcodeproj/project.pbxproj
  iOS/issue-tracker/issue-tracker/Controller/AddLabelViewController.swift
  iOS/issue-tracker/issue-tracker/Controller/LabelViewController.swift
  iOS/issue-tracker/issue-tracker/Model/NetworkManager.swift
  iOS/issue-tracker/issue-tracker/Model/UserDTO/IssueList.swift
  iOS/issue-tracker/issue-tracker/Supporting Files/Assets.xcassets/failure.imageset/Contents.json
  iOS/issue-tracker/issue-tracker/Supporting Files/Assets.xcassets/failure.imageset/redIcon.png
  iOS/issue-tracker/issue-tracker/Supporting Files/Assets.xcassets/success.imageset/Contents.json
  iOS/issue-tracker/issue-tracker/Supporting Files/Assets.xcassets/success.imageset/greenIcon.png
  iOS/issue-tracker/issue-tracker/View/Alert/CustomAlertView.swift
  iOS/issue-tracker/issue-tracker/View/IssueList/IssueTableViewCell.swift
  iOS/issue-tracker/issue-tracker/View/IssueList/LabelsCollectionView.swift
  iOS/issue-tracker/issue-tracker/View/IssueListViewController.swift
  iOS/issue-tracker/issue-tracker/ViewModel/AddLabelViewModel.swift
  iOS/issue-tracker/issue-tracker/ViewModel/IssueDetailViewModel.swift
  iOS/issue-tracker/issue-tracker/ViewModel/IssueListViewModel.swift
  iOS/issue-tracker/issue-tracker/ViewModel/MilestoneViewModel.swift
  iOS/issue-tracker/issue-tracker/ViewModel/NewIssueViewModel.swift
Labels: enhancement, iOS

#99 [iOS] complement tableView cell and the other features
  iOS/issue-tracker/issue-tracker/Controller/LabelViewController.swift
  iOS/issue-tracker/issue-tracker/Controller/MilestoneViewController.swift
  iOS/issue-tracker/issue-tracker/Model/UserDTO/PatchIssue.swift
  iOS/issue-tracker/issue-tracker/View/IssueList/IssueTableViewCell.swift
  iOS/issue-tracker/issue-tracker/View/IssueListViewController.swift
  iOS/issue-tracker/issue-tracker/View/Label/LabelTableViewCell.swift
  iOS/issue-tracker/issue-tracker/View/Milestone/MilestoneTableViewCell.swift
  iOS/issue-tracker/issue-tracker/ViewModel/IssueListViewModel.swift
  iOS/issue-tracker/issue-tracker/ViewModel/MilestoneViewModel.swift
Labels: enhancement, iOS
